####################################################
# Make Function
####################################################


# dir , lib name , suffix ,configure args
define auto_build_lib
	@echo "[1;33m" ">>>>>>> Build File: $(2)$(3)" "[0;39m" ;
	@set -x;
	@tar -zxf $(1)/$(2)$(3) -C $(1)/ ;
	@cd $(1)/$(2) && ./configure $(4) && make && make install;
endef















