




# dir , lib name , configure args
define auto_build_lib
	@echo "[1;33m" ">>>>>>> Enter DIR:$(1)" "[0;39m" ;
	@set -x;
	@tar -zxf $(1)/$(2).tar.gz -C $(1)/ ;
	@cd $(1)/$(2) && ./configure $(3) && make && make install;
endef















